services:
  - type: web
    name: youtube-sentiment-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9 